import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
      </Head>
      <main class={styles.main}>
      <nav class="bg-sm bg-gray-700 place-content-center justify  content-center flex flex-row items-center justify-center space-x-2">
        <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl px-4 md:px-6 py-2.5">
            <a href="#" class="inline-block 
place-items-center mt-6 mr-50 rounded-md bg-gray-700 px-3 py-2 m-500 text-center text-sm font-semibold uppercase text-white transition duration-200 ease-in-out hover:bg-gray-900">Home</a>
          <a href="#" class="inline-block 
place-items-center mt-6 mr-50 rounded-md bg-gray-700 px-3 py-2 m-500 text-center text-sm font-semibold uppercase text-white transition duration-200 ease-in-out hover:bg-gray-900">About Me</a>
          <a href="#" class="inline-block 
place-items-center mt-6 mr-50 rounded-md bg-gray-700 px-3 py-2 m-500 text-center text-sm font-semibold uppercase text-white transition duration-200 ease-in-out hover:bg-gray-900">Contact</a>
        </div>
      </nav>
    <div class=" flex flex-col bg-sm items-center pt-2  bg-gray-700">
      <h1 class="mt-10 bg-gradient-to-r from-blue-600 to-green-500 text-transparent bg-clip-text flex justify-center font-bold ">Hiroku</h1>
      <p class="break-all font-regular text-xs text-gray-300  ">Welcome To Hiroku. This project is for me to improve me web development skills by learning.</p>
     <p class="break-all font-regular text-xs pt-1 text-gray-300  ">Whenever I have free time I will update the website more and more.</p>
    </div>
    <div class="bg-sm bg-gray-700 pt-4 place-content-center justify  content-center flex flex-row items-center pb-60 justify-center space-x-2">
            <button class="inline-block 
place-items-center mt-6 rounded-md bg-gray-800 px-3 py-2.5 m-100 text-center text-sm font-semibold lowercase text-white transition duration-200 ease-in-out hover:bg-gray-900">
  <i class="fa fa-github mr-2"></i>
      Github
 </button>
      <button class="inline-block 
place-items-center mt-6 mr-50 rounded-md bg-gray-800 px-3 py-2.5 m-500 text-center text-sm font-semibold lowercase text-white transition duration-200 ease-in-out hover:bg-gray-900">
  <i className="fa fa-instagram mr-2"></i>
      Instagram
 </button>
      <button className="inline-block 
place-items-center mt-6 mr-50 rounded-md bg-gray-800 px-3 py-2.5 m-500 text-center text-sm font-semibold lowercase text-white transition duration-200 ease-in-out hover:bg-gray-900">
  <i className="fa fa-dribbble mr-2"></i>
      Dribbble
 </button>
    </div>
    <div  className="bg-sm bg-gray-700 place-content-center justify  content-center flex flex-row items-center justify-center ">
          <button className="inline-block 
place-items-center mt-6 mr-50 rounded-md px-3 py-1 m-500 text-center text-lg font-semibold uppercase text-white transition duration-200 ease-in-out hover:bg-gray-900">
  <i className="fa fa-angle-double-down"></i>
      
 </button>
    </div>
      </main>
    </>
  )
}
